openshift-s2i/s2i-wildfly

test/run
@bparees it seems like the incremental build is currently broken for JBoss, I saw same error when restoring artifacts about 'mv', will need to investigate more.
=> Fix polling for running container in test/run

.sti/bin/assemble, wfbin/standalone.conf
This reverts commit 707e010fcff191d015978b90942cb13ea845136d.
=> Revert "Add JRebel support"

Dockerfile
I replaced the OpenJDK 1.7 with the 1.8 version. Tested with a program that was compiled with Java 8 and contains streams https://github.com/sebplorenz/OpenShift-Wildfly-Java8 -> works
=> OpenJDK 1.8

8.1/Dockerfile
Updated maven version to 3.3.3 and Wildfly version extracted to an ENV variable
=> Updated to maven 3.3.3

README.md
Forgot this in the recent pull Request.
=> added docker pull command for Wildfly 10 Docker image

10.0/Dockerfile, 10.0/contrib/wfcfg/standalone.xml, 10.0/s2i/bin/usage, README.md
Since today Wildfly 10.0.0CR5 was released, I updated the Wildlfy 10 image and configuration.
=> updated to Wildfly 10.0.0CR5

10.0/Dockerfile
fixes https://github.com/openshift/sti-wildfly/issues/67
=> switch to wf10 final

10.0/Dockerfile, 8.1/Dockerfile, 9.0/Dockerfile
This change also combines consecutive ENV calls to reduce layers created during the build.
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>
=> Download archives using https

.travis.yml, README.md
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>
=> Add configuration for Travis-CI

10.0/Dockerfile, 8.1/Dockerfile, 9.0/Dockerfile, README.md
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>
=> Update references to repository from sti-wildfly to s2i-wildfly

10.0/s2i/bin/assemble, 8.1/s2i/bin/assemble, 9.0/s2i/bin/assemble
FIxes error messages shown in comment on #95
=> Make errors on chmod/chgrp while copy deployments silent

10.0/s2i/bin/assemble, 8.1/s2i/bin/assemble, 9.0/s2i/bin/assemble
=> Configurable ARTIFACT_DIR

10.0/s2i/bin/assemble, 10.1/s2i/bin/assemble, 8.1/s2i/bin/assemble, 9.0/s2i/bin/assemble
to be consistent with other parts of the assembly.
Fixes https://github.com/openshift-s2i/s2i-wildfly/issues/104
=> Changed JBOSS_HOME with /wildfly

10.0/contrib/wfbin/standalone.conf, 10.1/contrib/wfbin/standalone.conf, 8.1/contrib/wfbin/standalone.conf, 9.0/contrib/wfbin/standalone.conf
fixes https://github.com/openshift-s2i/s2i-wildfly/issues/106
=> set OPENSHIFT_SMTP_HOST if it is not explicitly set

10.0/contrib/wfcfg/standalone.xml, 10.1/contrib/wfcfg/standalone.xml, 8.1/contrib/wfcfg/standalone.xml, 9.0/contrib/wfcfg/standalone.xml
https://github.com/openshift-s2i/s2i-wildfly/issues/111
=> enable spec property replacement

10.0/contrib/wfbin/standalone.conf, 10.0/contrib/wfcfg/standalone.xml, 10.1/contrib/wfbin/standalone.conf, 10.1/contrib/wfcfg/standalone.xml, 8.1/contrib/wfbin/standalone.conf, 8.1/contrib/wfcfg/standalone.xml, 9.0/contrib/wfbin/standalone.conf, 9.0/contrib/wfcfg/standalone.xml
fixes https://github.com/openshift-s2i/s2i-wildfly/issues/128
=> setup openshift default datasource env var properly

10.0/Dockerfile, 10.1/Dockerfile, 8.1/Dockerfile, 9.0/Dockerfile
=> add a label pointing to the deployments dir

.travis.yml, hack/build.sh, hack/common.mk
fixes https://github.com/openshift-s2i/s2i-wildfly/issues/133
=> update shell syntax to support mac bash

11.0/contrib/wfcfg/standalone.xml
Synchronises some updates over from the updated WF 11 standalone.xml config.
=> Reference correct schema versions for WildFly 11.0.0.Final

README.md
https://github.com/openshift-s2i/s2i-wildfly/issues/147
=> add known issues in the README

10.0/s2i/bin/assemble, 10.1/s2i/bin/assemble, 11.0/s2i/bin/assemble
fixes https://github.com/openshift-s2i/s2i-wildfly/issues/153
=> fix java_home env var

14.0/Dockerfile, 14.0/s2i/bin/usage
fixes https://github.com/openshift-s2i/s2i-wildfly/issues/173
=> bump to 14.0.1

10.0/s2i/bin/assemble, 10.1/s2i/bin/assemble, 11.0/s2i/bin/assemble, 12.0/s2i/bin/assemble, 13.0/s2i/bin/assemble, 14.0/s2i/bin/assemble, 15.0/s2i/bin/assemble, 8.1/s2i/bin/assemble, 9.0/s2i/bin/assemble
=> Hide unnecessary error message when not files found in configuration/

15.0/Dockerfile
fixes https://github.com/openshift-s2i/s2i-wildfly/issues/181
=> move wf15 to jdk11

.travis.yml
Required for latest s2i changes.
/assign @bparees
=> Upgrade travis golang to 1.10

16.0/contrib/wfcfg/standalone.xml
In #185 I missed a few configuration updates that came with the WildFly 16.0.0.Final update. This PR adds them.
=> Fix WildFly 16 standalone.xml configuration
